// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyComuqsFrASzqIMabg0wgT4jvWh3ijLHQo',
    appId: '1:806273053476:web:eb3ddc3ce3861eede5f9b1',
    messagingSenderId: '806273053476',
    projectId: 'teamgrid-f812a',
    authDomain: 'teamgrid-f812a.firebaseapp.com',
    storageBucket: 'teamgrid-f812a.firebasestorage.app',
    measurementId: 'G-23S5CX0CVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfoGjr-Z_GoeOHwUnJI2lfSKi-b53KvOc',
    appId: '1:806273053476:android:ebb38c28c2f92db8e5f9b1',
    messagingSenderId: '806273053476',
    projectId: 'teamgrid-f812a',
    storageBucket: 'teamgrid-f812a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnssbRLz97zJasmF3dzTbkgF12BFt5TNU',
    appId: '1:806273053476:ios:c5aeab7ff44d1a2be5f9b1',
    messagingSenderId: '806273053476',
    projectId: 'teamgrid-f812a',
    storageBucket: 'teamgrid-f812a.firebasestorage.app',
    iosBundleId: 'com.example.teamgrid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnssbRLz97zJasmF3dzTbkgF12BFt5TNU',
    appId: '1:806273053476:ios:c5aeab7ff44d1a2be5f9b1',
    messagingSenderId: '806273053476',
    projectId: 'teamgrid-f812a',
    storageBucket: 'teamgrid-f812a.firebasestorage.app',
    iosBundleId: 'com.example.teamgrid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyComuqsFrASzqIMabg0wgT4jvWh3ijLHQo',
    appId: '1:806273053476:web:e9b282ca3311e6f8e5f9b1',
    messagingSenderId: '806273053476',
    projectId: 'teamgrid-f812a',
    authDomain: 'teamgrid-f812a.firebaseapp.com',
    storageBucket: 'teamgrid-f812a.firebasestorage.app',
    measurementId: 'G-YCDWB51JY2',
  );
}
